; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=test
AppVersion=1.0
Encryption=True
AppId={{2E3C8478-7451-4E13-ADB7-81D16906FF82}
Password=openwall
DefaultDirName=c:\test

[Files]
Source: "Z:\tmp\test.txt"; DestDir: "{app}"; Flags: ignoreversion
